# Generated by Django 4.1.2 on 2023-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_kyc_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('marrried', 'Married')], max_length=13, null=True),
        ),
    ]
