# Generated by Django 4.1.2 on 2023-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_kyc_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='recommended_by',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
