# Generated by Django 4.1.2 on 2023-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_recommended_by_alter_kyc_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
