# Generated by Django 4.1.2 on 2023-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
