# Generated by Django 4.1.2 on 2023-10-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_pin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_card',
            field=models.ImageField(upload_to='image'),
        ),
    ]
