# Generated by Django 4.1.2 on 2023-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_kyc_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
