# Generated by Django 4.1.2 on 2023-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_kyc_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_select',
            field=models.CharField(blank=True, choices=[('national id card', 'National ID Card'), ('drivers licence', 'Drivers Licence'), ('international passport', 'International Passport')], max_length=25, null=True),
        ),
    ]
