# Generated by Django 4.1.2 on 2023-10-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs_data',
            old_name='upper_Limit',
            new_name='upper_limit',
        ),
    ]
