# Generated by Django 4.1.2 on 2023-10-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_upper_limit_ecs_data_upper_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='ecs_data',
            options={'verbose_name_plural': 'Ecs_data'},
        ),
    ]
