# Generated by Django 4.1.2 on 2023-11-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_alter_bills_options_alter_ecs_data_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
