# Generated by Django 4.1.2 on 2023-10-03 02:15

from django.db import migrations, models
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=8, max_length=16, prefix='00', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('month', models.DateTimeField()),
                ('year', models.DateTimeField()),
                ('cvv', models.IntegerField(default=419)),
                ('card_type', models.CharField(default='visa', max_length=100)),
                ('card_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=13)),
                ('transfer_type', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit')], max_length=10)),
                ('receiver', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('description', models.TextField(default='School Fees', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
