# Generated by Django 4.1.2 on 2023-10-03 02:20

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_creditcard_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=16, max_length=16, prefix='', unique=True),
        ),
    ]
