# Generated by Django 4.1.2 on 2023-10-25 18:53

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=3, prefix='', unique=True),
        ),
    ]
