# Generated by Django 4.1.2 on 2023-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Transaction', max_length=200, null=True),
        ),
    ]
